name: LumiROM Tools Ui 8.5

on:
  workflow_dispatch:
    inputs:
      STOCK_DEVICE:
        description: "Put the Model of your phone, remember it starts with SM-"
        required: true
        default: "SM-A325F"
      USE_UI_8_TETHERING_APEX:
        description: "Set True if your kernel BPF version is lower than 5.10"
        required: true
        default: "False"

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:

    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install required packages
      run: |
        sudo apt update -q
        sudo apt install -y -q \
          p7zip-full lz4 android-sdk-libsparse-utils \
          python3 python3-pip zipalign unzip default-jre openjdk-17-jdk brotli e2fsprogs zstd aria2
        pip3 install -q liblp tgcrypto pyrogram gdown huggingface_hub hf_xet
        chmod +x bin/erofs-utils/extract.erofs
        chmod +x bin/erofs-utils/mkfs.erofs

    - name: Setup directories
      run: |
        chmod +x scripts/setup_directories.sh
        chmod +x scripts/zip_creation.sh
        chmod +x scripts/Knox_script.sh
        bash scripts/setup_directories.sh FIRMWARE WORK OUT
    
    - name: Set build environment
      shell: bash
      run: |
        echo "STOCK_DEVICE=${{ github.event.inputs.STOCK_DEVICE }}" >> $GITHUB_ENV
        echo "USE_UI_8_TETHERING_APEX=${{ github.event.inputs.USE_UI_8_TETHERING_APEX }}" >> $GITHUB_ENV
        echo "OUTPUT_FILESYSTEM=erofs" >> $GITHUB_ENV
        echo "LUMIROM_VERSION=8.6.1" >> $GITHUB_ENV

        echo "OUT_DIR=$PWD/OUT" >> $GITHUB_ENV
        echo "WORK_DIR=/dev/shm/WORK" >> $GITHUB_ENV
        echo "FIRM_DIR=$PWD/FIRMWARE" >> $GITHUB_ENV
        echo "DEVICES_DIR=$PWD/LumiROM/Devices" >> $GITHUB_ENV
        echo "APKTOOL=$PWD/bin/apktool/apktool.jar" >> $GITHUB_ENV
        echo "VNDKS_COLLECTION=$PWD/LumiROM/vndks" >> $GITHUB_ENV
        echo "BUILD_PARTITIONS=product,vendor,odm,system_ext,system" >> $GITHUB_ENV

    - name: Check repo
      shell: bash
      env:
        LUMIROM_BUILD: ${{ secrets.LUMIROM_BUILD }}
        OFFICIAL_HASH: ${{ secrets.OFFICIAL_HASH }}
      run: |
        source scripts/LumiROM.sh
        IS_OFFICIAL


    - name: Download firmware
      shell: bash
      run: |
        source scripts/LumiROM.sh
        source "$DEVICES_DIR/$STOCK_DEVICE/config"
        DOWNLOAD_FIRMWARE "$TARGET_DEVICE" "$FIRM_DIR"

    - name: Extract firmware
      shell: bash
      run: |
        source scripts/LumiROM.sh
        EXTRACT_FIRMWARE "FIRMWARE"
        PREPARE_PARTITIONS "FIRMWARE"
        EXTRACT_FIRMWARE_IMG "FIRMWARE"

    - name: Apply vendor patches
      shell: bash
      run: |
        source scripts/LumiROM.sh
        DISABLE_FBE "FIRMWARE"
        DISABLE_FDE "FIRMWARE"
        DELETE_ICCC "FIRMWARE"
        DEBLOAT_VENDOR "FIRMWARE"
        PATCH_FSTAB_EROFS "FIRMWARE"

    - name: Apply stock config
      shell: bash
      run: |
        source scripts/LumiROM.sh
        APPLY_STOCK_CONFIG "FIRMWARE"

    - name: Debloat ROM
      shell: bash
      run: |
        source scripts/LumiROM.sh
        DEBLOAT "FIRMWARE"

    - name: Apply features
      shell: bash
      run: |
        source scripts/LumiROM.sh
        APPLY_FEATURES "FIRMWARE"

    - name: Apply LumiBombs
      shell: bash
      run: |
        source scripts/LumiROM.sh
        LUMI_BOMBS "FIRMWARE"

    - name: Update Build ID
      shell: bash
      run: |
        source scripts/LumiROM.sh
        APPENDING_DISPLAY_ID "FIRMWARE"

    - name: Install stock framework-res
      shell: bash
      run: |
        source scripts/LumiROM.sh
        INSTALL_FRAMEWORK \
          "FIRMWARE/system/system/framework/framework-res.apk"

    - name: Decompile framework jars
      shell: bash
      run: |
        source scripts/LumiROM.sh
        DECOMPILE "$APKTOOL" \
          "FIRMWARE/system/system/framework/ssrm.jar" "$WORK_DIR" &
        DECOMPILE "$APKTOOL" \
          "FIRMWARE/system/system/framework/services.jar" "$WORK_DIR" &
        wait

    - name: Patch Knox
      shell: bash
      run: |
        source scripts/Knox_script.sh
        PATCH_SSRM "$WORK_DIR/ssrm"
        PATCH_KNOX_GUARD "$WORK_DIR/services"
        PATCH_FLAG_SECURE "$WORK_DIR/services"
        PATCH_SECURE_FOLDER "$WORK_DIR/services"
        PATCH_PRIVATE_SHARE "$WORK_DIR/services"
        DISABLE_SIGNATURE_VERIFICATION "$WORK_DIR/services"

    - name: Recompile framework
      shell: bash
      run: |
        source scripts/LumiROM.sh
        RECOMPILE "$APKTOOL" "$WORK_DIR/ssrm" \
          "FIRMWARE/system/system/framework" "$WORK_DIR" &
        RECOMPILE "$APKTOOL" "$WORK_DIR/services" \
          "FIRMWARE/system/system/framework" "$WORK_DIR" &
        wait
        cp -fv "$WORK_DIR"/*.jar \
          "FIRMWARE/system/system/framework/"

    - name: Build ROM
      shell: bash
      run: |
        source scripts/LumiROM.sh
        BUILD_IMG "FIRMWARE" "$OUTPUT_FILESYSTEM" "$OUT_DIR"
        IMG_TO_BROTLI "$OUT_DIR" "TMP"

    - name: Update updater-script
      shell: bash
      run: |
        source scripts/zip_creation.sh
        UPDATE_ZIP_SCRIPT "FIRMWARE"
        
    - name: Prepare flashable zip
      shell: bash
      run: |
        source scripts/zip_creation.sh
        FLASHABLE_ZIP_CREATION
   
    #- name: Upload ROM to Hugging Face
    #  env:
       # HF_TOKEN: ${{ secrets.HF_TOKEN }}
       # HF_XET_HIGH_PERFORMANCE: "1"
     # run: |
       # DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        #continue-on-error: hf buckets sync ./template hf://buckets/Zears14/lumifiles/out/$DATE/ --include "*.zip"

    - name: Upload to Gofile
      run: |
          # Busca el archivo zip de la ROM
          ROM_ZIP=$(find out/target/product/a22/ -name "*.zip" | head -n 1)
          if [ -z "$ROM_ZIP" ]; then
            echo "No se encontró ningún archivo ZIP para subir."
            exit 1
          fi
          echo "Subiendo $ROM_ZIP a Gofile..."
          # Sube a Gofile y extrae el enlace de descarga
          RESPONSE=$(curl -F "file=@$ROM_ZIP" https://gofile.io)
          DOWNLOAD_LINK=$(echo $RESPONSE | jq -r '.data.downloadPage')
          echo "--------------------------------------------------"
          echo "DESCARGA TU ROM AQUÍ: $DOWNLOAD_LINK"
          echo "--------------------------------------------------"
          
    - name: Cleanup
      run: |
        sudo rm -rf *
